apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: POGGERS
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
  - port: 21
    name: port-http
    protocol: TCP
    targetPort: 21
  - port: 10100
    name: port-pasv
    protocol: TCP
    targetPort: 10100
...
