apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
spec:
  selector:
    matchLabels:
      app: influx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influx
    spec:
      volumes:
      - name: influx-storage
        persistentVolumeClaim:
          claimName: influx-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: influx
        image: influx:k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influx-storage
          mountPath: /var/lib/influxdb
        - name: dockersock
          mountPath: var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: influx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: POGGERS
spec:
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 192.168.99.100
  selector:
    app: influx
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
...
