apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: POGGERS
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 443
      name: port-https
      protocol: TCP
      targetPort: 443
    - port: 80
      name: port-http
      protocol: TCP
      targetPort: 80
...
