apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: mysql-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  storageClassName: mysql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  storageClassName: influx-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-claim
spec:
  storageClassName: influx-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
