apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influx-svc:8086
    secureJsonData:
      token: token
    jsonData:
      version: Flux
      organization: school21
      defaultBucket: school21
      tlsSkipVerify: true
